/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { getOptionsForVote } from "../utils/getRandomPokemon";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [ids, updateIds] = useState(() => getOptionsForVote())
  const [firstEle, secondEle] = ids
  const firstPokemon = trpc.useQuery(['pokemon.get-pokemon-by-id', { id: Number(firstEle) }])
  const secondPokemon = trpc.useQuery(['pokemon.get-pokemon-by-id', { id: Number(secondEle) }])

  const voteForRoundest = (selected: number) => {
    updateIds(getOptionsForVote())
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen w-screen flex flex-col justify-center dark:bg-gray-800 dark:text-white bg-gray-200 items-center">
        <div className="text-2xl text-center">
          Which Pokemon is Rounder?
        </div>
        <div className="p-2"></div>
        <div className="border rounded p-8 flex justify-between max-w-2xl items-center capitalize">

          <div className="w-64 h-64 flex flex-col text-center justify-center items-center capitalize mt-[-2rem]">
            {firstPokemon.isLoading ? "Loading.." : (
              <>
                <img src={`${firstPokemon.data?.sprites.front_default}`} alt={`${firstPokemon.data?.name}'s sprite`} className='w-[13rem]' />
                <div className="text-xl text-center pb-1">{firstPokemon.data?.name}</div>
                <button className="mb-2 px-2 flex w-max mx-auto border border-slate-200 rounded-lg transition-all hover:bg-white hover:text-black" onClick={() => voteForRoundest((Number(firstEle)))}>Rounder</button>
              </>
            )}
          </div>
          <div className="p-8">Vs</div>
          <div className="w-64 h-64 flex flex-col justify-center text-center items-center capitalize mt-[-2rem]">
            {secondPokemon.isLoading ? "Loading.." : (
              <>
                <img src={`${secondPokemon.data?.sprites.front_default}`} alt={`${secondPokemon.data?.name}'s sprite`} className='w-[13rem]' />
                <div className="text-xl text-center pb-1">{secondPokemon.data?.name}</div>
                <button className="mb-2 px-2 flex w-max mx-auto border border-slate-200 rounded-lg transition-all hover:bg-white hover:text-black" onClick={() => voteForRoundest(Number(secondEle))}>Rounder</button>
              </>
            )}
          </div>
        </div>
      </div>

    </>
  );
};

export default Home;


